data_ingestion: 
  data_path : "https://drive.google.com/uc?id=1EGhVkCwO5lk9FakKrW2-0T3UuZFMKoC5"
  feature_names : 
    target : label
    dependent : text
  train_test_split:
    test_size: 0.25
    random_state: 42

data_preprocessing: 
  train_data_path : ./data/raw/train.csv
  test_data_path : ./data/raw/test.csv

feature_engineering: 
  tf_idf : 
    max_features: 1500
    min_df: 3
  train_data_path : ./data/interim/train.csv
  test_data_path : ./data/interim/test.csv


model_building:
  random_forest: 
    n_estimators : 300
    class_weight : "balanced_subsample"
  train_data_path : ./data/processed/train.csv

model_evaluation : 
  test_data_path : ./data/processed/test.csv
  model_file_path : ./model/model.pkl
  metrics_json_output : ./reports/metrics.json