data_ingestion: 
  data_path : 'https://raw.githubusercontent.com/vikashishere/Datasets/main/spam.csv'
  feature_names : 
    target : v1
    dependent : v2
  train_test_split:
    test_size: 0.25
    random_state: 42

data_preprocessing: 
  train_data_path : ./data/raw/train.csv
  test_data_path : ./data/raw/test.csv
  target : v1
  dependent : v2

feature_engineering: 
  tf_idf : 
    max_features: 35
  train_data_path : ./data/interim/train_processed.csv
  test_data_path : ./data/interim/test_processed.csv
  target : v1
  dependent : v2

model_building:
  random_forest: 
    n_estimators: 50
    random_state: 42
  train_data_path : ./data/processed/train_tfidf.csv

model_evaluation : 
  test_data_path : ./data/processed/test_tfidf.csv
  model_file_path : ./model/model.pkl
  metrics_json_output : ./reports/metrics.json